import { NonIdealState, Spinner } from '@blueprintjs/core';
import { CubeVizContextProvider } from '@cubeviz/core';
import Head from 'next/head';
import { useCubeApi } from '../hooks/use-cube-api';
import { EChartsXYChart } from '@cubeviz/echarts';

export default function Home() {
  const cubeApi = useCubeApi();
  return (
    <>
      <Head>
        <title>Cubeviz Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CubeVizContextProvider
          cubejsApi={cubeApi}
          renderError={(error) => (
            <NonIdealState
              icon="error"
              title={error.name}
              description={error.message}
            />
          )}
          loadingDisplay={
            <NonIdealState icon={<Spinner />} title="Loading cubes..." />
          }
        >
          <EChartsXYChart
            x="Countries.continent"
            y="Countries.totalPopulation"
            chartType="bar"
          />
        </CubeVizContextProvider>
      </main>
    </>
  );
}
